name: mesa-core22
base: core22
summary: mesa drivers for the glvnd-core22 graphics snap
description: |
  A content snap containing the dri drivers for core22
compression: lzo
version: "0.01"

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x
  - build-on: riscv64

parts:
  i386-repo:
    plugin: nil
    override-pull: |
      if [ ${CRAFT_TARGET_ARCH} = "amd64" ]; then
        dpkg --add-architecture i386
        apt-get update
      fi

  dri:
    # Userspace drivers
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libegl-mesa0
      - libdrm-intel1
      - mesa-vulkan-drivers
      - libglx-mesa0
    prime:
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libdrm_*
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libEGL_*
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libGLX_*
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libpciaccess*
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libvulkan_*
      - usr/share/glvnd
      - usr/share/vulkan
      - usr/share/drirc.d

  va:
    # Video Acceleration APIs
    #   o libva.so.2
    #   o libvdpau.so.1
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - libva2
      - libva-x11-2
      - libva-drm2
      - libva-wayland2
      - libvdpau1
      - va-driver-all
      - vdpau-driver-all
    prime:
      - etc/vdpau_wrapper.cfg
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libigdgmm*
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libva*
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libvdpau*
      - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/vdpau

  dri-i386:
    # Userspace drivers
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - on amd64:
        - libgl1-mesa-dri:i386
        - libegl-mesa0:i386
        - libdrm-intel1:i386
        - mesa-vulkan-drivers:i386
        - libglx-mesa0:i386
    override-prime: |
      if [ ${CRAFT_TARGET_ARCH} = "amd64" ]; then craftctl default; fi
    prime:
      - usr/lib/i386-linux-gnu/dri
      - usr/lib/i386-linux-gnu/libdrm_*
      - usr/lib/i386-linux-gnu/libEGL_*
      - usr/lib/i386-linux-gnu/libGLX_*
      - usr/lib/i386-linux-gnu/libpciaccess*
      - usr/lib/i386-linux-gnu/libvulkan_*
      - usr/share/glvnd
      - usr/share/vulkan
      - usr/share/drirc.d

  va-i386:
    # Video Acceleration API
    #   o libva.so.2
    #   o libvdpau.so.1
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - on amd64:
        - libva2:i386
        - libva-x11-2:i386
        - libva-drm2:i386
        - libva-wayland2:i386
        - libvdpau1:i386
        - va-driver-all:i386
        - vdpau-driver-all:i386
    override-prime: |
      if [ ${CRAFT_TARGET_ARCH} = "amd64" ]; then craftctl default; fi
    prime:
      - etc/vdpau_wrapper.cfg
      - usr/lib/i386-linux-gnu/libigdgmm*
      - usr/lib/i386-linux-gnu/libva*
      - usr/lib/i386-linux-gnu/libvdpau*
      - usr/lib/i386-linux-gnu/vdpau

slots:
  glvnd-driver-core22:
    interface: content
    source:
      read:
        - $SNAP
