name: Snap

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Snap:
    runs-on: ubuntu-latest

    timeout-minutes: 45

    strategy:
      matrix:
        platform:
        - amd64
        # Not ready yet - armhf
        # Not ready yet - arm64
        # Not ready yet - ppc64el
        # Not ready yet - s390x

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # needed for version determination

    - name: Build and publish the snap
      id: build-snap
      uses: canonical/actions/build-snap@release
      with:
        architecture: ${{ matrix.platform }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
        snapcraft-channel: candidate
        launchpad-credentials: ${{ secrets.LAUNCHPAD_CREDENTIALS }}
        publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
        publish-channel: edge/pr${{ github.event.number }}

    - name: Test the snap
      if: ${{ false && matrix.platform == 'amd64' }}
      run: |
        sudo snap install --dangerous ${{ steps.build-snap.outputs.snap-path }}
        sudo snap install mir-test-tools --channel 22/stable
        sudo snap connect mir-test-tools:login-session-control
        sudo snap connect mir-test-tools:graphics-core22 mesa-core22

        sudo adduser $USER video
        sudo adduser $USER input

        sg video "
          sg input '
            mir-test-tools.smoke-test
          '
        "
